// <auto-generated />

namespace P02Ef4.Models
{
  public class Bed
    {
        public int Id { get; set; }

        // Attributes
        public int Number { get; set; }

        public int GardenId { get; set; }

        // 0-1
        // public Garden Garden { get; set; }

        // 0-Many
        // public List<CropAssignment> CropAssignments { get; set; }
    }
}
