// <auto-generated />

namespace P02Ef4.Models
{
  public class Garden
    {
        public int Id { get; set; }

        // Attributes
        public string Name { get; set; }

        // 0-1
        // public Garden Garden { get; set; }

        // 0-Many
        // public List<CropAssignment> CropAssignments { get; set; }
    }
}
